### ISSUE TITLE
Reverse pipeline?

### ISSUE THREAD

**Issue by laggingreflex** [mindeavor/es-pipeline-operator#40] opened 2016-06-27 15:43 UTC
This is regular:

    "hello" |> doubleSay |> capitalize |> exclaim

How about reverse pipeline with a new operator: `<|`

    exclaim <| capitalize <| doubleSay <| "hello"

[There were previous talks about Elixir-like syntax](https://github.com/mindeavor/es-pipeline-operator/issues/4)

>     // Elixir style
    run("hello") |> withThis(10) |> andThis(20)
    // is equivalent to
    andThis( withThis( run("hello"), 10 ), 20 )

>:-1: Gives a new semantic meaning to what looks like a normal function call. For example, withThis(10) is no longer just calling that function with one argument    
:-1: Putting the left-hand side as the first argument to the right-hand side is pretty arbitrary.

With reverse pipline (and additional feature of applying arguments from the right) it could be written as

    run("hello") |> withThis <| 10 |> andThis <| 20

When both operators are used in an expression like this, the resverse pipe accepting arguments from the **right** would apply them ***after*** the arguments coming from the regular pipeline from the left. 

Regular pipeline takes higher precedence than reverse pipeline.

    run("hello") |> withThis <| 10 |> andThis <| 20
    ____________    ______________
    ______________________________    _____________

Thoughts?

**Comment by Mouvedia** [comment] 2016-07-14 02:57
dupe of #3

**Comment by TehShrike** [comment] 2016-09-22 12:47
Closing in favor of #3

**Closed by TehShrike** 2016-09-22 12:47 UTC
Labels: duplicate
